name = "Arcanus"
filename = "arcanus-1.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3464/131/arcanus-1.14.jar"
hash-format = "murmur2"
hash = "1119041502"

[update]
[update.curseforge]
file-id = 3464131
project-id = 517833
release-channel = "beta"
