name = "Arcanus"
filename = "arcanus-1.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/896/arcanus-1.13.jar"
hash-format = "murmur2"
hash = "2256111112"

[update]
[update.curseforge]
file-id = 3460896
project-id = 517833
release-channel = "beta"
