name = "Arcanus"
filename = "arcanus-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/574/arcanus-1.12.jar"
hash-format = "murmur2"
hash = "2148972580"

[update]
[update.curseforge]
file-id = 3459574
project-id = 517833
release-channel = "beta"
