name = "megane"
filename = "megane-5.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3466/649/megane-5.4.0.jar"
hash-format = "murmur2"
hash = "3066226378"

[update]
[update.curseforge]
file-id = 3466649
project-id = 408118
release-channel = "beta"
