name = "megane"
filename = "megane-5.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/534/megane-5.3.0.jar"
hash-format = "murmur2"
hash = "2408252503"

[update]
[update.curseforge]
file-id = 3454534
project-id = 408118
release-channel = "beta"
