name = "Quarry Reborn"
filename = "quarry-reborn-1.17-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/202/quarry-reborn-1.17-0.4.0.jar"
hash-format = "murmur2"
hash = "2373244620"

[update]
[update.curseforge]
file-id = 3459202
project-id = 511254
release-channel = "beta"
