name = "Rhino"
filename = "rhino-1605.1.2-build.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/188/rhino-1605.1.2-build.40.jar"
hash-format = "murmur2"
hash = "821559348"

#[update]
#[update.curseforge]
#file-id = 3426188
#project-id = 416294
#release-channel = "beta"
