name = "Tech Reborn"
filename = "TechReborn-5.0.6-beta+build.94.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/679/TechReborn-5.0.6-beta+build.94.jar"
hash-format = "murmur2"
hash = "1248434213"

[update]
[update.curseforge]
file-id = 3424679
project-id = 233564
release-channel = "beta"
